name: "Access Request Form"
description: "Request access to private repositories"
title: "[Access Request] <!-- Your Name Here -->"
labels: ["access-request"]
assignees:
  - stephenpring
  - jprb-walton
  - jmulcahy11
  - matthew-mizielinski

body:
  - type: input
    id: UserId
    attributes:
      label: "Github User name"
    validations:
      required: true
  - type: input
    id: Name
    attributes:
      label: "Name"
    validations:
      required: true
  - type: input
    id: institution
    attributes:
      label: "Institution"
    validations:
      required: true      
  - type: input
    id: Reason
    attributes:
      label: "Purpose of access request"
      description: |
  Access to the following private repositories is available:
  
  - CMIP7-documentation
  - CMIP7-AFT-Simulations
  - CDDS-simulation-metadata
  - CDDS-CMIP7-processing
  
If you would like general access to all repositories, please indicate that below.
  Otherwise, please specify which repositories you would like access to.
      placeholder: "e.g. I need access to XYZ repository to contribute documentation and share simulation results"
    validations:
      required: true
