name: "CMIP7 Experiment Review"
description: 'Documentation template to be completed for the Review of a CMIP7 Experiment'
title: 'Issue: <Brief description here>'
    
body:

-   id: Description 
    type: textarea
    attributes:
        label: Reviewer Name
        value: |
            
            Please add your name here. 
            Please fill out the Experiment Review Section Below.             
            
   
-   id: review_note
    type: markdown
    attributes:
        value: Please Do Not Change the information in the following text area as this is there to support review.
        
-   id: review_information
    type: textarea
    attributes:
        label: Review Documentation
        value: |
            Please input the following information below.
            
            # ROSE suite being reviewed [suite-id](https://code.metoffice.gov.uk/trac/roses-u/browser/a/a/0/0/0/): experiment name
            
            ## Description
            
            **Science / technical review**:
            | Task | Date completed | Notes | Reviewed by |
            |---|---|---|---|
            | Diagnostic setup correctly configured for this experiment | | Only relevant if this experiment has specific diagnostic requirements  **todo: link to diagnostic documentation when ready** | |
            | Suite revision reviewed corresponds to that in suite description provided in Job Documentation Template |  |  |  |
            | All suite changes committed to repository |  | Suite revision reviewed: rNNNN |  |
            | Changes from predecessor suite are documented and consistent with CMIP experimental design (refer to appropriate [MIP protocol paper](https://gmd.copernicus.org/articles/special_issue1315.html)) | | | |
            | The job is consistent with other related runs (e.g. other ensemble members, historical->SSP continuations) | | | |
            | Start and end dates are correct (see [Experiment Guidance](https://github.com/UKNCSP/CMIP7-simulations/blob/main/Experiment_Guidance.md)) | | | |
            | Job descended from correct GC5 / UKESM job: baseline configuration suite ID and revision should be listed under appropriate config release pages (tbd) | | This is to minimise the propagation of errors discovered after the first runs have begun. | |
            | If setup deviates from experimental protocol, have these exceptions been recorded above? |  |  |  |
            | Does suite use branches for any component model? | | | |
            | If so has this code been accepted for a future release of the component model? | | | |
            | Have all forcing datasets been reviewed? See [Forcing Data Pages](https://code.metoffice.gov.uk/trac/UKESM/wiki/UKESMAncilWG). | | | |

-   id: review_note
    attributes:
        label: Review Assessment
        description: Are you happy to approve this Experiment?
        options:
            - "Approved"
            - "Not Approved"
    validations:
        required: true
    type: dropdown
