name: 'General Issue'
description: 'New Issue for new CMIP7 simulation'
title: 'Issue: <Brief description here>'
labels:
    - HadGEM-GC5-N96ORCA1
    - HadGEM-GC5-N640ORCA12
    - UKESM1.3-N96ORCA1
    - UKESM2.0-N96ORCA1
body:

-   id: Description 
    type: textarea
    attributes:
        value: |
            ## General Issue Report

            Please provide details about your issue. 
            Please fill out the a Jobs Description Template (can I link to template from here). 
            Reviewer Template to be linked from here?

-   id: issue_type
    attributes:
        label: Issue Type
        description: What kind of issue are you reporting?
        options:
            - Bug Report
            - Feature Request
            - Documentation Issue
            - Data Quality Issue
            - Process Improvement
            - Other
    validations:
        required: true
    type: dropdown




