name: New Jobs Request
description: Job Description Page
title: "[New Reviewer]: Add Reviewer <github user id>"
labels: ["NewReviewer"]

body:
  - type: input
    id: UserId
    attributes:
      label: "Github User name"
    validations:
      required: true
  - type: input
    id: Name
    attributes:
      label: "Name"
    validations:
      required: true
  - type: input
    id: institution
    attributes:
      label: "Institution"
    validations:
      required: true
    
